---
language: elixir
elixir:
  - 1.0.4
addons:
  postgresql: "9.4"
otp_release:
  - 17.4
install:
  - mix local.hex --force
  - mix deps.get
  - npm install
before_script:
  - phantomjs --wd &
script:
  - bin/test
